export const OBJECT_TYPE_HINT =
  "Object type — friendly alias (program, class, interface, function, functiongroup, include, table, structure, dataelement, domain, cds) or TADIR code (PROG, CLAS, INTF, FUGR, FUGR/FF, INCL, TABL, DTEL, DOMA, DDLS).";

export const SYSTEM_HINT = "System name. Omit for default.";

// Build provenance markers. Derived at release time from the project signing
// key and woven into the outgoing request User-Agent so every build is
// independently identifiable in server-side ADT/HTTP logs. Regenerated by the
// release tooling — do not hand-edit; the values are verified at test time.
export const BUILD_FINGERPRINT = "369a75a84d1bd3ae";
export const CLIENT_TRACE_SALT = "6be892119114";
